ProGestor.WebApplication.final/Areas/Admin/Controllers/StatusProjectController.cs
using Microsoft.AspNetCore.Mvc;
using ProGestor.Common.Entities;
using ProGestor.Common.Interfaces;
using ProGestor.WebApplication.final.viewModels;

namespace ProGestor.WebApplication.final.Areas.Admin.Controllers;

[Area("Admin")]
public class StatusProjectController : Controller
{
    private readonly IStatusProjectRepository _statusProjectRepository;

    public StatusProjectController(IStatusProjectRepository statusProjectRepository)
    {
        _statusProjectRepository = statusProjectRepository;
    }

    public async Task<IActionResult> Index()
    {
        var listStatus = await _statusProjectRepository.GetAll();
        var list = new StatusProjectViewModel()
        {
            StatusProjects = listStatus.ToList()
        };
        
        return View(list);
    }

    [HttpPost]
    public async Task<IActionResult> Add(StatusProject statusProject)
    {
        if (String.IsNullOrEmpty(statusProject.name) || String.IsNullOrEmpty(statusProject.name))
        {
            return Json(new { id = 1, message = "Asegurese de completar todos los campos" });
        }
        
        await _statusProjectRepository.Add(statusProject);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> UpdateStatus(int id)
    {
        var getStatus  = await _statusProjectRepository.GetById(id);

        TempData["Id"] = getStatus.Id;
        var getModel = new StatusProjectViewModel()
        {
            Id = getStatus.Id,
            name = getStatus.name
        };
        
        return PartialView("_UpdateStatus",getModel);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateStatus(StatusProject statusProject)
    {
        var Id = Convert.ToInt32(TempData["Id"].ToString());
        var getById = await _statusProjectRepository.GetById(Id);

        getById.name = statusProject.name;
        var update = await _statusProjectRepository.Update(getById);
        
        if (update)
        {
            return RedirectToAction("Index");
        }
        else
        {
            return BadRequest();
        }
    }
    
    
    [HttpPost]
    public async Task<IActionResult> Remove(int id)
    {
        var remove = await _statusProjectRepository.Remove(id);

        if (remove)
        {
            return Json(new { id = 1 });
        }
        
        
        return Json(new { id = 2 });
    }
}

ProGestor.WebApplication.final/Areas/Admin/Views/StatusProject/Index.cshtml
@model ProGestor.WebApplication.final.viewModels.StatusProjectViewModel
@{
    ViewData["Title"] = "Proyectos";
    ViewData["Caption"] = "Estados del proyecto";
}

<div class="content-body default-height">
	<div class="container-fluid">
		<div class="page-titles">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="javascript:void(0)">Proyectos</a></li>
				<li class="breadcrumb-item active"><a href="javascript:void(0)">Estados del proyecto</a></li>
			</ol>
		</div>
		<!-- Row -->
		<div class="row">
			<div class="col-xl-12">
				<div class="row">
					<div class="col-xl-4">
						<div class="filter cm-content-box box-primary">
							<div class="content-title">
								<div class="cpa">
									Agregar nuevo estado
								</div>
								<div class="tools">
									<a href="javascript:void(0);" class="expand SlideToolHeader"><i class="fal fa-angle-down"></i></a>
								</div>
							</div>
							<div class="cm-content-body form excerpt">
								<div class="card-body">
									<form asp-controller="StatusProject" asp-area="Admin" asp-action="Add">
										<div class="mb-3">
											<label class="form-label">Nombre del estado</label>
											<input type="text" name="name" value="@(Model?.name ?? "")" class="form-control" placeholder="Ejemp: En proceso">
										</div>
										<button type="submit" class="btn btn-primary">Guardar</button>
									</form>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-8">
						<div class="filter cm-content-box box-primary">
							<div class="content-title">
								<div class="cpa">
									Lista de estados
								</div>
								<div class="tools">
									<a href="javascript:void(0);" class="expand SlideToolHeader"><i class="fal fa-angle-down"></i></a>
								</div>
							</div>
							<div class="cm-content-body publish-content form excerpt">
								<div class="card-body py-3">
									<div class="table-responsive">
										<table class="table table-striped verticle-middle table-responsive-sm">
											<thead>
												<tr>
													<th scope="col" class="text-black">S.No</th>
													<th scope="col" class="text-black">Nombre</th>
													<th scope="col" class="text-black text-end">Acción</th>
												</tr>
											</thead>
											<tbody>
												
											@foreach (var item in Model.StatusProjects)
											{
												<tr>
													
													<td>@item.Id</td>
													<td>@item.name</td>

													<td class="text-end">
														<a href="javascript:void(0);">Editar</a>
														<span>|</span>
														<a href="javascript:void(0);">Actualizar</a>
														<span>|</span>
														<a href="javascript:void(0);">Eliminar</a>
														<span>|</span>

													</td>
												</tr>
												
											}
												
											</tbody>
											
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--**********************************
Content body end
***********************************-->
@section gymove_style
	{
	<!-- Start Page Level CSS -->
	<link rel="stylesheet" href="~/gymove/vendor/chartist/css/chartist.min.css">
	<link href="~/gymove/vendor/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
	<!-- End Page Level CSS -->
}

@section gymove_script
	{
		<!--**********************************
		Scripts
		***********************************-->
		<script src="~/gymove/vendor/global/global.min.js"></script>
		<script src="~/gymove/vendor/bootstrap-select/js/bootstrap-select.min.js"></script>
		<!-- Dashboard 1 -->
		<script src="~/gymove/js/dashboard/cms.js"></script>
		<script src="~/gymove/js/custom.min.js"></script>
		<script src="~/gymove/js/deznav-init.js"></script>
}

ProGestor.WebApplication.final/Areas/Admin/Views/StatusProject/_UpdateStatus.cshtml
@model ProGestor.WebApplication.final.viewModels.StatusProjectViewModel
@{
    ViewData["Title"] = "Proyectos";
    ViewData["Caption"] = "Estados del proyecto";
}
<div class="bootstrap-modal">
    <!-- Button trigger modal -->
    <!-- Modal -->
    <div class="modal-header">
        <h5 class="modal-title">Modificar estado</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal">
        </button>
    </div>
    <form asp-action="UpdateStatus" asp-area="Admin" asp-controller="StatusProject" method="post">
        <div class="modal-body">
            <input type="text" name="name" value="@(Model?.name ?? "")" class="form-control">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger light" data-bs-dismiss="modal">Cerrar</button>

            <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </div>
    </form>
</div>