ProGestor.WebApplication.final/Areas/Admin/Controllers/BillingController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProGestor.Common.Entities;
using ProGestor.Common.Interfaces;
using ProGestor.WebApplication.final.viewModels;

namespace ProGestor.WebApplication.final.Areas.Admin.Controllers;

[Area("Admin")]
public class BillingController : Controller
{

    private readonly IInvoiceRepository _invoiceRepository;
    private readonly IProjectRepository _projectRepository;
    private readonly IProjectTypeRepository _projectTypeRepository;
    private readonly IStatusProjectRepository _statusProjectRepository;
    private readonly UserManager<User> _userManager;

    public BillingController(IInvoiceRepository repository, IProjectRepository projectRepository, IProjectTypeRepository projectTypeRepository, IStatusProjectRepository statusProjectRepository, UserManager<User> userManager)
    {
        this._invoiceRepository = repository;
        _projectRepository = projectRepository;
        _projectTypeRepository = projectTypeRepository;
        _statusProjectRepository = statusProjectRepository;
        _userManager = userManager;
    }
    
    [HttpGet]
    public async Task<ActionResult> Index()
    {
        var getAll = await _invoiceRepository.GetAll();
        
        var getProjectList = new InvoiceViewModel()
        {
            Users = _userManager.Users.ToList(),
            Invoices = getAll.ToList()
            
        };


        return View();
    }


    [HttpGet]
    public async Task<ActionResult> AddBilling()
    {
        var getProjectList = new InvoiceViewModel()
        {
            Users = _userManager.Users.ToList()
        };
        
        return View(getProjectList);
    }
    [HttpPost]
    public async Task<ActionResult> AddBilling(Invoice invoice)
    {
       var result = await _invoiceRepository.Add(invoice);

       if (result)
       {
           return null;
       }

       return NotFound();
    }
}

ProGestor.WebApplication.final/Areas/Admin/Controllers/ProjectController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProGestor.Common.Entities;
using ProGestor.Common.Interfaces;
using ProGestor.WebApplication.final.viewModels;

namespace ProGestor.WebApplication.final.Areas.Admin.Controllers;


[Area("Admin")]
public class ProjectController : Controller
{

    private readonly IProjectRepository _projectRepository;
    private readonly IProjectTypeRepository _projectTypeRepository;
    private readonly IStatusProjectRepository _statusProjectRepository;
    private readonly UserManager<User> _userManager;

    public ProjectController(IProjectRepository projectRepository, 
        IProjectTypeRepository projectTypeRepository, IStatusProjectRepository statusProjectRepository, UserManager<User> userManager)
    {
        _projectRepository = projectRepository;
        _projectTypeRepository = projectTypeRepository;
        _statusProjectRepository = statusProjectRepository;
        _userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var result = await _projectRepository.GetAllProject();
        return View(result);
    }


    [HttpGet]
    public async Task<IActionResult> AddProject()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity!;
        var actualUser = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        
        var getProjectList = new ProjectViewModel()
        {
            ProjectTypes = _projectTypeRepository.GetAll().Result.ToList(),
            StatusProjects = _statusProjectRepository.GetAll().Result.ToList(),
            Users = _userManager.Users.Where(x => x.Id != actualUser!.Value).ToList()
        };

        return View(getProjectList);
    }

    [HttpGet]
    public async Task<ActionResult> UpdateStatusProject(int projectId)
    {

        TempData["projectId"] = projectId;
        var listOfStatus = await _statusProjectRepository.GetAll();
        var getStatus = new ProjectViewModel
        {
            StatusProjects = listOfStatus.ToList()
        };

        return PartialView("_UpdateStatusProject", getStatus);
    }
    
    
    [HttpPost]
    public async Task<ActionResult> UpdateStatusProject(int projectId, Project project)
    {

        int projectCode = Convert.ToInt32(TempData["projectId"]);

        var projectUpdate = await _projectRepository.GetById(projectCode);

        projectUpdate.StatusProjectId = projectId;

        var result = await _projectRepository.Update(projectUpdate);

        if (result)
        {
            return RedirectToAction("Index");
        }
        
        return BadRequest();
    }

    [HttpGet]
    public async Task<ActionResult> UpdateDateTime(int projectId)
    {
        TempData["ProjectId"] = projectId;
        var getProject = await _projectRepository.GetById(projectId);

        var getFirstProject = new ProjectViewModel()
        {
            DateProjectStart = getProject.DateProjectStart,
            DateProjectEnd = getProject.DateProjectEnd
        };

        return PartialView("_UpdateDateTime", getFirstProject);
    }

    [HttpPost]
    public async Task<ActionResult> UpdateDateTime(DateTime DateProjectStart, DateTime DateProjectEnd)
    {
        int projectId = Convert.ToInt32(TempData["ProjectId"]);

        var project = await _projectRepository.GetById(projectId);

        if (DateProjectStart.Year >=  DateTime.Now.Year)
        {
            project.DateProjectStart = DateProjectStart;
        }

        if (DateProjectEnd.Year >= DateTime.Now.Year)
        {
            project.DateProjectEnd = DateProjectEnd;
        }
        
        var isUpdate = await _projectRepository.Update(project);

        if (isUpdate)
        {
            return RedirectToAction("Index");
        }
        return BadRequest();


    }
    
    [HttpGet]
    public async Task<ActionResult> UpdateEstimation(int projectId)
    {
        TempData["ProjectId"] = projectId;
        var getProject = await _projectRepository.GetById(projectId);

        var getFirstProject = new ProjectViewModel
        {
            quoter = getProject.quoter,
        };

        return PartialView("_UpdateEstimation", getFirstProject);
    }

    [HttpPost]
    public async Task<ActionResult> UpdateEstimation(double amount)
    {
        var projectId = Convert.ToInt32(TempData["ProjectId"]);

        var getProject = await _projectRepository.GetById(projectId);

        if (amount > 0)
        {
           getProject.quoter = amount;
        }

        var result = await _projectRepository.Update(getProject);

        if (result)
        {
            return RedirectToAction("Index");
        }
        
        return BadRequest();
    }
    [HttpPost]
    public async Task<ActionResult> RemoveProject(int ProjectId)
    {

        var getProject = await _projectRepository.GetById(ProjectId);

        getProject.Status = false;

        var wasRemove = await _projectRepository.Update(getProject);

        if (wasRemove)
        {
            return new JsonResult(new { id = 1 });
        }

        return BadRequest();
    }
    
    
    [HttpPost]
    public async Task<IActionResult> AddProject(Project project)
    {
        project.Status = true;
        if (project.UserId != null)
        {
            var addProject = await _projectRepository.Add(project);
            if (addProject)
            {
                return RedirectToAction("Index");
            }
        }
        else
        {
            return RedirectToAction("AddProject");
        }
        
        return BadRequest();

    }
    
}

ProGestor.WebApplication.final/Areas/Admin/Controllers/ProjectTypeController.cs
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using ProGestor.Common.Entities;
using ProGestor.Common.Interfaces;
using ProGestor.WebApplication.final.viewModels;

namespace ProGestor.WebApplication.final.Areas.Admin.Controllers;

[Area("Admin")]
public class ProjectTypeController : Controller
{

    private readonly IProjectTypeRepository _projectTypeRepository;

    public ProjectTypeController(IProjectTypeRepository projectTypeRepository)
    {
        _projectTypeRepository = projectTypeRepository;
    }
    
    
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var projectTypeList = await _projectTypeRepository.GetAll();
        var projectType = new ProjectTypeViewModel()
        {
            ProjectTypes = projectTypeList.ToList()
        };
        
        return View(projectType);
    }


    [HttpPost]
    public async Task<IActionResult> Add(ProjectType projectType)
    {
        if (String.IsNullOrEmpty(projectType.name) || String.IsNullOrEmpty(projectType.description))
        {
            return Json(new { id = 1, message = "Asegure de completar todos los campos" });
        }
        
        var addType = await _projectTypeRepository.Add(projectType);

        if (addType)
        {
            return RedirectToAction("Index");
        }

        else return BadRequest();

    }

    [HttpGet]
    public async Task<IActionResult> UpdateType(int id)
    {
        var getType = await _projectTypeRepository.GetById(id);
        
        TempData["Id"] = getType.Id;

        var type = new ProjectTypeViewModel()
        {
            Name = getType.name,
            Description = getType.description
        };

        return PartialView("_UpdateType", type);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateType(ProjectType projectType)
    {
        int getId = Convert.ToInt32(TempData["Id"]);

        var update = await _projectTypeRepository.GetById(getId);

        update.name = projectType.name;
        update.description = projectType.description;

        var isTrue = await _projectTypeRepository.Update(update);

        if (isTrue)
        {
            return RedirectToAction("Index");
        }
        
        return BadRequest();
    }



    [HttpPost]
    public async Task<IActionResult> Remove(int id)
    {
        var getType = await _projectTypeRepository.Remove(id);

        if (getType)
        {
            return Json(new { id = 1, message = "Se ha eliminado con exito" });
        }
        return Json(new { id = 2, message = "No se ha podido eliminar el registro" });
    }
    
    
}

ProGestor.WebApplication.final/Areas/Admin/Controllers/UserController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProGestor.Common.Entities;

namespace ProGestor.WebApplication.final.Areas.Admin.Controllers;


[Area("Admin")]
public class UserController : Controller
{

    private readonly UserManager<User> _userManager;

    public UserController(UserManager<User> userManager)
    {
        _userManager = userManager;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity!;
        var actualUser = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        var test = User.Claims.ToList();
        var userList = _userManager.Users
            .Include(x => x.Gender)
            .Include(c => c.City)
            .Where(x => x.Id != actualUser!.Value).ToList();
        
        return View(userList);
    }
}

ProGestor.WebApplication.final/Views/Shared/ProGestor/_Footer.cshtml
<footer class="footer">
    <div class="copyright">
        @* <p>Copyright © Designed &amp; Developed by <a href="http://dexignzone.com/" target="_blank">DexignZone</a> 2023</p> *@
    </div>
</footer>

ProGestor.WebApplication.final/Views/Shared/ProGestor/_Meta.cshtml
<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="author" content="DexignZone">
<meta name="robots" content="">

<meta name="keywords" content="admin, admin dashboard, admin template, bootstrap, bootstrap 5, bootstrap 5 admin template, fitness, fitness admin, modern, responsive admin dashboard, sales dashboard, sass, ui kit, web app">
<meta name="description" content="Discover Gymove, the ultimate fitness solution that is designed to help you achieve a healthier lifestyle with its cutting-edge features and personalized programs. Gymove is a fully mobile-responsive admin dashboard template that provides the perfect blend of exercise, nutrition, and motivation. Begin your fitness journey today with Gymove and visit DexignZone for more information.">

<meta property="og:title" content="Gymove  - Fitness Bootstrap Admin Dashboard Template">
<meta property="og:description" content="Discover Gymove, the ultimate fitness solution that is designed to help you achieve a healthier lifestyle with its cutting-edge features and personalized programs. Gymove is a fully mobile-responsive admin dashboard template that provides the perfect blend of exercise, nutrition, and motivation. Begin your fitness journey today with Gymove and visit DexignZone for more information.">
<meta property="og:image" content="http://products.imageslelo.com/images/gymove_ogimage.png">
<meta name="format-detection" content="telephone=no">

<!-- Mobile Specific -->
<meta name="viewport" content="width=device-width, initial-scale=1">

ProGestor.WebApplication.final/Views/Shared/ProGestor/_NavHeader.cshtml
<div class="nav-header">
    <a href="@Url.Action("Index","Home")" class="brand-logo" aria-label="ProGestor">
        <img class="logo-abbr" src="~/gymove/images/logo.png" alt="">
        <img class="logo-compact" src="~/gymove/images/logo-text.png" alt="">
        <img class="brand-title" src="~/gymove/images/logo-text.png" alt="">
    </a>
    <div class="nav-control">
        <div class="hamburger">
            <span class="line"></span><span class="line"></span><span class="line"></span>
        </div>
    </div>
</div>

ProGestor.WebApplication.final/Views/Shared/ProGestor/_PreLoader.cshtml
<div id="preloader">
    <div class="sk-three-bounce">
        <div class="sk-child sk-bounce1"></div>
        <div class="sk-child sk-bounce2"></div>
        <div class="sk-child sk-bounce3"></div>
    </div>
</div>

ProGestor.WebApplication.final/Views/Shared/ProGestor/_Sidebar.cshtml
<div class="deznav">
    <div class="deznav-scroll">
        <ul class="metismenu" id="menu">
            <li>
                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false">
                    <i class="flaticon-381-networking"></i>
                    <span class="nav-text">Proyectos</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-area="Admin" asp-controller="Project" asp-action="AddProject">Crear proyecto</a></li>
                    <li><a asp-area="Admin" asp-controller="Project" asp-action="Index">Listado de proyectos</a></li>
                    <li><a asp-area="Admin" asp-controller="StatusProject" asp-action="Index">Estados del proyecto</a></li>
                    <li><a asp-area="Admin" asp-controller="ProjectType" asp-action="Index">Tipos de proyectos</a></li>
                </ul>
            </li>
 <li>
     <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false">
         <i class="flaticon-381-television"></i>
         <span class="nav-text">Facturación</span>
     </a>
     <ul aria-expanded="false">
         <li><a asp-area="Admin" asp-controller="Billing" asp-action="Index">Facturas</a></li>
         <li><a asp-area="Admin" asp-controller="Billing" asp-action="AddBilling">Crear factura</a></li>
         <li>
             <a class="has-arrow" href="javascript:void(0)" aria-expanded="false">Otras opciones</a>
             <ul aria-expanded="false">
                 <li><a href="@Url.Action("", "")">Métodos de pago</a></li>
                 <li><a href="@Url.Action("", "")">Reclamaciones</a></li>
                 <li><a href="@Url.Action("", "")">Ajustes de cuentas</a></li>
             </ul>
         </li>
         </ul>
            <li>
            
                <a class="has-arrow" href="javascript:void(0)" aria-expanded="false">     <i class="flaticon-381-compact-disc-1"></i>Programar actividad</a>
                <ul aria-expanded="false">
                    <li><a href="@Url.Action("", "")">Crear actividad</a></li>
                    <li><a href="@Url.Action("", "")">Listado de actividades</a></li>
                </ul>
            </li>
                    <li>
                        <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false">
                            <i class="flaticon-381-compact-disc-1"></i>
                            <span class="nav-text">Diseños<span class="badge badge-danger badge-xs ms-1">Diseños</span></span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="@Url.Action("", "")">Crear diseño</a></li>
                        </ul>
                    </li>
                    
            <li>
                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false">
                    <i class="flaticon-381-compact-disc-1"></i>
                    <span class="nav-text">Reportes<span class="badge badge-danger badge-xs ms-1">Reportes</span></span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="@Url.Action("", "")">Listado de facturas</a></li>
                    <li><a href="@Url.Action("", "")">Listado de clientes</a></li>
                    <li><a href="@Url.Action("", "")">Ganancias</a></li>
                    <li><a href="@Url.Action("", "")">Proyectos por trimestres</a></li>
                </ul>
            </li>
            
            <li>
                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false">
                    <i class="flaticon-381-compact-disc-1"></i>
                    <span class="nav-text">Administración</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-area="Admin" asp-controller="User" asp-action="Index">Listado de empleados</a></li>
                    <li><a asp-area="Identity" asp-page="/Account/Register"> Crear empleados</a></li>
                </ul>
            </li>
        </ul>

        
        @*            <li> *@
 @*                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false"> *@
 @*                    <i class="flaticon-381-briefcase"></i> *@
 @*                    <span class="nav-text">CMS<span class="badge badge-danger badge-xs ms-1">NEW</span></span> *@
 @*                </a> *@
 @*                <ul aria-expanded="false"> *@
 @*                    <li><a href="@Url.Action("", "")">Content</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Add Content</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Menus</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Email Template</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Add Email</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Blog</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Add Blog</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Blog Category</a></li> *@
 @*                </ul> *@
 @*            </li> *@
 @*            <li> *@
 @*                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false"> *@
 @*                    <i class="flaticon-381-controls-3"></i> *@
 @*                    <span class="nav-text">Charts</span> *@
 @*                </a> *@
 @*                <ul aria-expanded="false"> *@
 @*                    <li><a href="@Url.Action("", "")">Flot</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Morris</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Chartjs</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Chartist</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Sparkline</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Peity</a></li> *@
 @*                </ul> *@
 @*            </li> *@
 @*            <li> *@
 @*                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false"> *@
 @*                    <i class="flaticon-381-internet"></i> *@
 @*                    <span class="nav-text">Bootstrap</span> *@
 @*                </a> *@
 @*                <ul aria-expanded="false"> *@
 @*                    <li><a href="@Url.Action("", "")">Accordion</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Alert</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Badge</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Button</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Modal</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Button Group</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">List Group</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Media Object</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Cards</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Carousel</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Dropdown</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Popover</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Progressbar</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Tab</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Typography</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Pagination</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Grid</a></li> *@
 @*         *@
 @*                </ul> *@
 @*            </li> *@
 @*            <li> *@
 @*                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false"> *@
 @*                    <i class="flaticon-381-heart"></i> *@
 @*                    <span class="nav-text">Plugins</span> *@
 @*                </a> *@
 @*                <ul aria-expanded="false"> *@
 @*                    <li><a href="@Url.Action("", "")">Select 2</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Nestedable</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Noui Slider</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Sweet Alert</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Toastr</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Jqv Map</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Lightgallery</a></li> *@
 @*                </ul> *@
 @*            </li> *@
 @*            <li> *@
 @*                <a href="@Url.Action("", "")" class="ai-icon" aria-expanded="false"> *@
 @*                    <i class="flaticon-381-settings-2"></i> *@
 @*                    <span class="nav-text">Widget</span> *@
 @*                </a> *@
 @*            </li> *@
 @*            <li> *@
 @*                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false"> *@
 @*                    <i class="flaticon-381-notepad"></i> *@
 @*                    <span class="nav-text">Forms</span> *@
 @*                </a> *@
 @*                <ul aria-expanded="false"> *@
 @*                    <li><a href="@Url.Action("", "")">Form Elements</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Wizard</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Editor</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Pickers</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Jquery Validate</a></li> *@
 @*                </ul> *@
 @*            </li> *@
 @*            <li> *@
 @*                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false"> *@
 @*                    <i class="flaticon-381-network"></i> *@
 @*                    <span class="nav-text">Table</span> *@
 @*                </a> *@
 @*                <ul aria-expanded="false"> *@
 @*                    <li><a href="@Url.Action("", "")">Bootstrap</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Datatable</a></li> *@
 @*                </ul> *@
 @*            </li> *@
 @*            <li> *@
 @*                <a class="has-arrow ai-icon" href="javascript:void(0)" aria-expanded="false"> *@
 @*                    <i class="flaticon-381-layer-1"></i> *@
 @*                    <span class="nav-text">Pages</span> *@
 @*                </a> *@
 @*                <ul aria-expanded="false"> *@
 @*                    <li><a href="@Url.Action("", "")">Register</a></li> *@
 @*                    <li><a href="@Url.Action("", "")">Login</a></li> *@
 @*                    <li> *@
 @*                        <a class="has-arrow" href="javascript:void(0)" aria-expanded="false">Error</a> *@
 @*                        <ul aria-expanded="false"> *@
 @*                            <li><a href="@Url.Action("", "")">Error 400</a></li> *@
 @*                            <li><a href="@Url.Action("", "")">Error 403</a></li> *@
 @*                            <li><a href="@Url.Action("", "")">Error 404</a></li> *@
 @*                            <li><a href="@Url.Action("", "")">Error 500</a></li> *@
 @*                            <li><a href="@Url.Action("", "")">Error 503</a></li> *@
 @*                        </ul> *@
 @*                    </li> *@
 @*                    <li><a href="@Url.Action("", "")">Lock Screen</a></li> *@
 @*                </ul> *@
 @*            </li> *@
        @* </ul>  *@
     </div> 
</div>